package com.stash.opusplayer.music.data.database.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "playlists")
data class PlaylistEntity(
    @PrimaryKey
    @ColumnInfo(name = "id")
    val id: String, // Use string ID for system playlists like "favorites"
    
    @ColumnInfo(name = "name")
    val name: String,
    
    @ColumnInfo(name = "description")
    val description: String? = null,
    
    @ColumnInfo(name = "image_url")
    val imageUrl: String? = null,
    
    @ColumnInfo(name = "is_public")
    val isPublic: Boolean = false,
    
    @ColumnInfo(name = "is_system")
    val isSystem: Boolean = false, // System playlists like Recently Played
    
    @ColumnInfo(name = "is_shuffle")
    val isShuffle: Boolean = false,
    
    @ColumnInfo(name = "repeat_mode")
    val repeatMode: String = "OFF", // OFF, ALL, ONE
    
    @ColumnInfo(name = "is_auto_generated")
    val isAutoGenerated: Boolean = false,
    
    @ColumnInfo(name = "total_tracks")
    val totalTracks: Int = 0,
    
    @ColumnInfo(name = "total_duration")
    val totalDuration: Long = 0,
    
    @ColumnInfo(name = "play_count")
    val playCount: Int = 0,
    
    @ColumnInfo(name = "last_played")
    val lastPlayed: Long? = null,
    
    @ColumnInfo(name = "creation_date")
    val creationDate: Long,
    
    @ColumnInfo(name = "date_modified")
    val dateModified: Long,
    
    @ColumnInfo(name = "tags_json")
    val tagsJson: String? = null, // JSON array of tags
    
    @ColumnInfo(name = "auto_update_rules_json")
    val autoUpdateRulesJson: String? = null // JSON rules for smart playlists
)
