package com.stash.opusplayer.music.domain.models

import com.stash.opusplayer.music.data.database.entities.PlaylistEntity

data class Playlist(
    val id: PlaylistId,
    val name: String,
    val description: String?,
    val imageUrl: String?,
    val isPublic: Boolean,
    val isSystem: Boolean,
    val isShuffle: Boolean,
    val repeatMode: RepeatMode,
    val isAutoGenerated: Boolean,
    val totalTracks: Int,
    val totalDuration: Long,
    val playCount: Int,
    val lastPlayed: Long?,
    val creationDate: Long,
    val dateModified: Long,
    val tags: List<String>,
    val autoUpdateRules: String?
)

@JvmInline
value class PlaylistId(val value: String)

enum class RepeatMode {
    OFF, ALL, ONE
}

fun PlaylistEntity.toDomainModel() = Playlist(
    id = PlaylistId(id),
    name = name,
    description = description,
    imageUrl = imageUrl,
    isPublic = isPublic,
    isSystem = isSystem,
    isShuffle = isShuffle,
    repeatMode = RepeatMode.valueOf(repeatMode),
    isAutoGenerated = isAutoGenerated,
    totalTracks = totalTracks,
    totalDuration = totalDuration,
    playCount = playCount,
    lastPlayed = lastPlayed,
    creationDate = creationDate,
    dateModified = dateModified,
    tags = tagsJson?.split(",")?.filter { it.isNotBlank() } ?: emptyList(),
    autoUpdateRules = autoUpdateRulesJson
)

fun Playlist.toEntity() = PlaylistEntity(
    id = id.value,
    name = name,
    description = description,
    imageUrl = imageUrl,
    isPublic = isPublic,
    isSystem = isSystem,
    isShuffle = isShuffle,
    repeatMode = repeatMode.name,
    isAutoGenerated = isAutoGenerated,
    totalTracks = totalTracks,
    totalDuration = totalDuration,
    playCount = playCount,
    lastPlayed = lastPlayed,
    creationDate = creationDate,
    dateModified = dateModified,
    tagsJson = tags.joinToString(","),
    autoUpdateRulesJson = autoUpdateRules
)
